### ISSUE TITLE
cloud-config instructions not being executed, system coming back with node unreachable

### ISSUE THREAD

**Issue by asimkhawaja** [DimensionDataCBUSydney/plumbery#25]
Hey Folks,
   I am unable to use cloud-config in my fittings file. Running with the -d setting shows that when plumbery tries to use cloud-config it get a node unreachable. 
I have based my simplified fittings file based on the more complex files in the samples project, so I might be missing something. 

Your guidance would be most appreciated.

--------------------------
Fittings file used:
-------------------------------
```yml
information:
    - "Setup mysql servers for testing on Ubuntu /Redhat "
links:
  documentation: https://plumbery.readthedocs.org/en/latest/tutorial.apache2.cluster.html

defaults:

  cloud-config:

    ssh_keys:
      rsa_private: |
        {{ key.rsa_private }}
      rsa_public: "{{ key.rsa_public }}"

    users:
      - default

      - name: ubuntu
        sudo: 'ALL=(ALL) NOPASSWD:ALL'

    disable_root: false
    ssh_pwauth: true

---

# London
locationId: AU10
regionId: dd-au

blueprints:

  - mysql:

      domain:
        name: BaaS_Test_AU10

        service: advanced

      ethernet:
        name: "baas_vlan"
        subnet: 10.0.0.0

      nodes:
        - mysqltesti_2:
           information : "mysql base node for ubuntu"
           appliance : 'CentOS 7'
           cloud-config:
              packages:
               - ntp
               - mysql-server
```

-----------------------------------------
plumbery output:
----------------------------------

```console
[root@localhost Development]# python -d -m plumbery asim_fittings.yaml prepare
Using polisher 'prepare'
Polishing all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
preparing node 'mysqltesti_2'
- not found
Worked for you in a blink locally, and for 1 seconds in the cloud
[root@localhost Development]# python -d -m plumbery asim_fittings.yaml deploy
Building all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
Creating network domain 'BaaS_Test_AU10'
- already there
Creating Ethernet network 'baas_vlan'
- already there
Creating node 'mysqltesti_2'
- in progress
Using polisher 'configure'
Polishing all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
Configuring blueprint 'mysql'
- waiting for nodes to be deployed
- nodes have been deployed
Configuring node 'mysqltesti_2'
Starting nodes from all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
Starting node 'mysqltesti_2'
- in progress
Using polisher 'prepare'
Polishing all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
preparing node 'mysqltesti_2'
- using cloud-config
- node is unreachable
Using polisher 'information'
Polishing all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
- examinating node 'mysqltesti_2'
Showing information
About this fittings plan:
- Setup mysql servers for testing on Ubuntu /Redhat
- documentation: https://plumbery.readthedocs.org/en/latest/tutorial.apache2.cluster.html
About 'mysqltesti_2':
- node is up and running
Worked for you for 6 seconds locally, and for 6 minutes in the cloud
[root@localhost Development]# python -d -m plumbery asim_fittings.yaml prepare
Using polisher 'prepare'
Polishing all blueprints
Plumbing at 'AU10' Australia - Melbourne MCP2 (Australia)
preparing node 'mysqltesti_2'
- using cloud-config
- node is unreachable
Worked for you in a blink locally, and for 2 seconds in the cloud

```
